# Personalize your website info here
title:            Zuzana
tagline:          'Lets start the party'
description:      'Website for Zuzana'
url:              http://zuzanatatarova.github.io
author:
  name:           'zuzana tatarova'
  url:            https://twitter.com/zuzana

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
